# Generated by Django 5.0.6 on 2024-07-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='preco_promotional',
            new_name='preco_promocional',
        ),
    ]
