# Generated by Django 5.0.6 on 2024-07-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_preco_marketing_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='preco_promocional',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='preço promocional'),
        ),
    ]
