# Generated by Django 5.0.6 on 2024-07-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.FloatField(default=0.0, verbose_name='preço unitário'),
            preserve_default=False,
        ),
    ]
