# Generated by Django 5.0.6 on 2024-07-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_price_marketing_promocional_product_price_marketing_promotional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
