version: '3.9'

services:
  djangoapp:
    container_name: django-app
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./django-app:/docker
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./env-files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
