version: '3.9'

services:
  app:
    container_name: django-blog
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web/assets:/data/web/assets/
      - ./data/web/uploads:/data/web/uploads/
    env_file:
      - ./env-files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./env-files/.env

